// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV3oTWvzfqKwOJGxnpOQ1heuEmOdT5Woo',
    appId: '1:1032636817245:web:0c289277893575cf7012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    authDomain: 'pomodoro-app-f720d.firebaseapp.com',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
    measurementId: 'G-1DDQYFWKPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdb9dRGn2rlOgyDfVvjcQas5xfu52tsGQ',
    appId: '1:1032636817245:android:972eecf650212c3e7012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmUkgbKGhRUrGAGKII7CkL3Fq1HTS_5VU',
    appId: '1:1032636817245:ios:1583bd24693e823a7012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmUkgbKGhRUrGAGKII7CkL3Fq1HTS_5VU',
    appId: '1:1032636817245:ios:ccf2ceefa8414cf37012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV3oTWvzfqKwOJGxnpOQ1heuEmOdT5Woo',
    appId: '1:1032636817245:web:45996e9dff4d99187012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    authDomain: 'pomodoro-app-f720d.firebaseapp.com',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
    measurementId: 'G-8MJM8GBDCS',
  );
}
