// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    const flavor = String.fromEnvironment('flavor');
    
    if (flavor == 'dev') {
      return _getCurrentPlatformDev();
    } else {
      return _getCurrentPlatformProd();
    }
  }

  static FirebaseOptions _getCurrentPlatformDev() {
    if (kIsWeb) {
      return webDev;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidDev;
      case TargetPlatform.iOS:
        return iosDev;
      case TargetPlatform.macOS:
        return macosDev;
      case TargetPlatform.windows:
        return windowsDev;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getCurrentPlatformProd() {
    if (kIsWeb) {
      return webProd;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidProd;
      case TargetPlatform.iOS:
        return iosProd;
      case TargetPlatform.macOS:
        return macosProd;
      case TargetPlatform.windows:
        return windowsProd;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Development environment options
  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyDRvJOzfAwg6V4Kfjt8_xk61NNKn8QKmgI',
    appId: '1:864390988828:web:xxxxx',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    authDomain: 'pomodoro-app-dev-ce8b6.firebaseapp.com',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDT6aqTA1mLHvvgum5sa0OCG0Y3FHhfl1M',
    appId: '1:864390988828:android:b3a260c2472d6f83834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyDRvJOzfAwg6V4Kfjt8_xk61NNKn8QKmgI',
    appId: '1:864390988828:ios:0a551e08c128e257834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
    iosBundleId: 'com.tkan66.poromodo.dev',
  );

  static const FirebaseOptions macosDev = FirebaseOptions(
    apiKey: 'AIzaSyDRvJOzfAwg6V4Kfjt8_xk61NNKn8QKmgI',
    appId: '1:864390988828:ios:0a551e08c128e257834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
    iosBundleId: 'com.tkan66.poromodo.dev',
  );

  static const FirebaseOptions windowsDev = FirebaseOptions(
    apiKey: 'AIzaSyDRvJOzfAwg6V4Kfjt8_xk61NNKn8QKmgI',
    appId: '1:864390988828:web:xxxxx',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    authDomain: 'pomodoro-app-dev-ce8b6.firebaseapp.com',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
  );

  // Production environment options
  static const FirebaseOptions webProd = FirebaseOptions(
    apiKey: 'AIzaSyDmUkgbKGhRUrGAGKII7CkL3Fq1HTS_5VU',
    appId: '1:1032636817245:web:xxxxx',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    authDomain: 'pomodoro-app-f720d.firebaseapp.com',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyDdb9dRGn2rlOgyDfVvjcQas5xfu52tsGQ',
    appId: '1:1032636817245:android:33a9d30896b9bb7b7012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
  );

  static const FirebaseOptions iosProd = FirebaseOptions(
    apiKey: 'AIzaSyDmUkgbKGhRUrGAGKII7CkL3Fq1HTS_5VU',
    appId: '1:1032636817245:ios:a8fdeb3ae4fbd1be7012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
    iosBundleId: 'com.tkan66.poromodo',
  );

  static const FirebaseOptions macosProd = FirebaseOptions(
    apiKey: 'AIzaSyDmUkgbKGhRUrGAGKII7CkL3Fq1HTS_5VU',
    appId: '1:1032636817245:ios:a8fdeb3ae4fbd1be7012b4',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
    iosBundleId: 'com.tkan66.poromodo',
  );

  static const FirebaseOptions windowsProd = FirebaseOptions(
    apiKey: 'AIzaSyDmUkgbKGhRUrGAGKII7CkL3Fq1HTS_5VU',
    appId: '1:1032636817245:web:xxxxx',
    messagingSenderId: '1032636817245',
    projectId: 'pomodoro-app-f720d',
    authDomain: 'pomodoro-app-f720d.firebaseapp.com',
    storageBucket: 'pomodoro-app-f720d.firebasestorage.app',
  );
}