// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-d34wyk2hr3-d0qEhZQUozbRAxuxadP8',
    appId: '1:864390988828:web:7a31a9e41dcfdfc9834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    authDomain: 'pomodoro-app-dev-ce8b6.firebaseapp.com',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
    measurementId: 'G-4935SZDFV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT6aqTA1mLHvvgum5sa0OCG0Y3FHhfl1M',
    appId: '1:864390988828:android:3cf212ba1f4af8f4834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRvJOzfAwg6V4Kfjt8_xk61NNKn8QKmgI',
    appId: '1:864390988828:ios:ee42525804f8c19d834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRvJOzfAwg6V4Kfjt8_xk61NNKn8QKmgI',
    appId: '1:864390988828:ios:93acbe88572dbefd834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-d34wyk2hr3-d0qEhZQUozbRAxuxadP8',
    appId: '1:864390988828:web:103918c0c7c388fb834bd9',
    messagingSenderId: '864390988828',
    projectId: 'pomodoro-app-dev-ce8b6',
    authDomain: 'pomodoro-app-dev-ce8b6.firebaseapp.com',
    storageBucket: 'pomodoro-app-dev-ce8b6.firebasestorage.app',
    measurementId: 'G-MPLGFV8VQ8',
  );
}
